export enum SessionStateValues {
    SESSION_INVALID = 0,
    SESSION_PRACTICE = 1,
    SESSION_TEST = 2,
    SESSION_QUALIFY = 3,
    SESSION_FORMATION_LAP = 4,
    SESSION_RACE = 5,
    SESSION_TIME_ATTACK = 6,
    SESSION_MAX = 7
}

export enum RaceStateValues {
    RACESTATE_INVALID = 0,
    RACESTATE_NOT_STARTED = 1,
    RACESTATE_RACING = 2,
    RACESTATE_FINISHED = 3,
    RACESTATE_DISQUALIFIED = 4,
    RACESTATE_RETIRED = 5,
    RACESTATE_DNF = 6,
    RACESTATE_MAX = 7
}